// @flow

const MESSAGES_LOADING = "MESSAGES_LOADING";
const MESSAGES_LOADED = "MESSAGES_LOADED";

const LIST_ALL_MESSAGES = "LIST_ALL_MESSAGES";
const GET_THE_MESSAGE = "GET_THE_MESSAGE";
const CREATE_NEW_MESSAGE = "CREATE_NEW_MESSAGE";
const DELETE_THE_MESSAGE = "DELETE_THE_MESSAGE";
const LIST_RECIPIENTS = "LIST_RECIPIENTS";

const SELECT_SCREEN = "SELECT_SCREEN";
const CLEAN_MESSAGE = "CLEAN_MESSAGE";

export {
  MESSAGES_LOADING,
  MESSAGES_LOADED,
  LIST_ALL_MESSAGES,
  GET_THE_MESSAGE,
  CREATE_NEW_MESSAGE,
  DELETE_THE_MESSAGE,
  LIST_RECIPIENTS,
  SELECT_SCREEN,
  CLEAN_MESSAGE
};
